language: go

go:
- 1.10.x

install:
# Install promtool and pin it at the latest stable version, currently 2.4.3
- PROMTOOL_URI=github.com/prometheus/prometheus/cmd/promtool;
  PROMTOOL_VERSION=2.4.3;
  go get -d $PROMTOOL_URI;
  git -C $GOPATH/src/$PROMTOOL_URI checkout -b $PROMTOOL_VERSION tags/v$PROMTOOL_VERSION;
  go install $PROMTOOL_URI

script:
- promtool check rules rules.d/*.yml
- promtool test rules tests/*.yml
