language: go

go:
- 1.10.x

install:
- PROMTOOL_URI=github.com/prometheus/prometheus/cmd/promtool;
  go get -d $PROMTOOL_URI;
  go install $PROMTOOL_URI

script:
- promtool check rules rules.d/*.yml
- promtool test rules tests/*.yml
